drop all OBJECTS;

CREATE TABLE IF NOT EXISTS mpa (
        mpa_id INTEGER NOT NULL PRIMARY KEY,
        mpa_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
        genre_id INTEGER NOT NULL PRIMARY KEY,
        genre_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
        film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        film_name varchar(300) NOT NULL,
        description varchar(600),
        release_date date NOT NULL,
        duration INTEGER NOT NULL,
        mpa_id INTEGER REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
        user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        login varchar(300) NOT NULL,
        user_name varchar(300),
        email varchar(300) NOT NULL,
        birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
        film_id INTEGER NOT NULL REFERENCES films (film_id),
        genre_id INTEGER NOT NULL REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
        film_id INTEGER NOT NULL REFERENCES films (film_id),
        user_id INTEGER NOT NULL REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS friend (
        user_id INTEGER NOT NULL REFERENCES users (user_id),
        friend_id INTEGER NOT NULL REFERENCES users (user_id)
);


